export enum Events {
  MINIMIZE_WINDOW = "MINIMIZE_WINDOW",
  MIXIMIZE_WINDOW = "MIXIMIZE_WINDOW",
  FULL_SCREEN = "FULL_SCREEN",
  CLOSE_WINDOW = "CLOSE_WINDOW",
  QUIT = "QUIT",
  COPY = "COPY",
  PASTE = "PASTE",
  SELECT_ALL = "SELECT_ALL",
  ZOOM_IN = "ZOOM_IN",
  ZOOM_OUT = "ZOOM_OUT",
  ZOOM_RESET = "ZOOM_RESET",
  TOOGLE_ABOUT = "TOOGLE_ABOUT",
  TOGGLE_DEVTOOLS = "TOGGLE_DEVTOOLS",
  UNDO = "UNDO",
  REDO = "REDO",
}

export enum ClipboardEvents {
  READ_TEXT = "READ_TEXT",
  WRITE_TEXT = "WRITE_TEXT",
  CLEAR = "CLEAR",
}

export enum DialogEvents {
  SHOW_OPEN_DIALOG = "SHOW_OPEN_DIALOG",
  SHOW_SAVE_DIALOG = "SHOW_SAVE_DIALOG",
}
